language: python
sudo: false
python:
    - "2.6"
    - "2.7"
#    - "3.2" removed because Coveralls/coverage fails on 3.2
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - pip install coveralls
script:
    - "python test_gnupg.py --no-doctests"
    - "coverage run test_gnupg.py --no-doctests"
after_success: coveralls
